/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.helidon.examples.openapigen.mp.client.api;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Set;

import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.MediaType;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.util.List;
import java.util.Map;
import io.helidon.examples.openapigen.mp.client.model.Message;

/**
 * Generated API
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 */
@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("")
public interface DefaultApi  {

    @GET
    @Path("/greet")
    @Produces({ "application/json" })
    Message greetGet() throws ApiException, ProcessingException;

    @PUT
    @Path("/greet/greeting")
    @Consumes({ "application/json" })
    void greetGreetingPut(Object body) throws ApiException, ProcessingException;

    @GET
    @Path("/greet/{name}")
    @Produces({ "application/json" })
    Message greetNameGet(@PathParam("name") String name) throws ApiException, ProcessingException;

    @GET
    @Path("/simple-greet")
    @Produces({ "application/json" })
    Message simpleGreetGet() throws ApiException, ProcessingException;

    @GET
    @Path("/simple-greet/{name}")
    @Produces({ "application/json" })
    Message simpleGreetNameGet(@PathParam("name") String name) throws ApiException, ProcessingException;
}
