/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.helidon.examples.openapigen.mp.client.api;

import java.util.List;
import java.util.Map;
import io.helidon.examples.openapigen.mp.client.model.Message;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import org.eclipse.microprofile.rest.client.RestClientBuilder;

import java.net.URL;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generated API Test
 *
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private static DefaultApi client;
    private static final String baseUrl = "http://localhost:8080";

    @BeforeAll
    public static void setup() throws MalformedURLException {
        client = RestClientBuilder.newBuilder()
                        .baseUrl(new URL(baseUrl))
                        .register(ApiException.class)
                        .build(DefaultApi.class);
    }

    
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void greetGetTest() throws Exception {
        //Message response = client.greetGet();
        //assertNotNull(response);
    }
    
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void greetGreetingPutTest() throws Exception {
        //void response = client.greetGreetingPut(body);
        //assertNotNull(response);
    }
    
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void greetNameGetTest() throws Exception {
        //Message response = client.greetNameGet(name);
        //assertNotNull(response);
    }
    
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void simpleGreetGetTest() throws Exception {
        //Message response = client.simpleGreetGet();
        //assertNotNull(response);
    }
    
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void simpleGreetNameGetTest() throws Exception {
        //Message response = client.simpleGreetNameGet(name);
        //assertNotNull(response);
    }
    
}
